# Generated by Django 5.0.4 on 2024-07-31 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Delivering', 'Delivering')], default='Pending', max_length=10)),
                ('quantity', models.IntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('cancel', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.useraccounts')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
    ]
