# Generated by Django 5.0.4 on 2024-08-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menu_discount'),
        ('orders', '0005_alter_order_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
            preserve_default=False,
        ),
    ]
