# Generated by Django 5.0.4 on 2024-08-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_review_title_remove_menu_category_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(to='menu.category'),
        ),
        migrations.AddField(
            model_name='menu',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.cuisine'),
        ),
    ]
