# Generated by Django 5.0.4 on 2024-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menu_category_remove_menu_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
