# Generated by Django 5.0.4 on 2024-08-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menu_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
