# Generated by Django 5.0.4 on 2024-10-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menu_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
