# Generated by Django 5.0.4 on 2024-06-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, default='bankrupt', max_length=255, null=True),
        ),
    ]
