# Generated by Django 5.0.4 on 2024-05-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
