# Generated by Django 5.0.4 on 2024-06-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_alter_borrow_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='balance_after_borrow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
