--* scalar subquery : returns a record with one raw and one column;
--* multi line subquery : returns multiple record with multiple raw and column;
--* co related subquery : in co related subquery there is a relation between inner(subquery) query and outer(main query) query;