# Generated by Django 5.0.4 on 2024-11-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='balance_after_trans',
            field=models.IntegerField(default=0),
        ),
    ]
