# Generated by Django 5.0.4 on 2024-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin')], default='Customer', max_length=10),
        ),
    ]
