# Generated by Django 5.0.4 on 2024-10-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_useraccounts_amount_useraccounts_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
