# Generated by Django 5.0.4 on 2024-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_alter_useraccounts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('WithDraw', 'WithDraw')], default='Deposit', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='trans_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
