# Generated by Django 5.0.4 on 2024-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specials',
            name='menu',
        ),
        migrations.AddField(
            model_name='specials',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='specials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='specials/images/'),
        ),
        migrations.AddField(
            model_name='specials',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specials',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
