# Generated by Django 5.0.4 on 2024-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=12)),
                ('instrument_type', models.CharField(choices=[('', 'Select a type'), ('guitar', 'Guitar'), ('piano', 'Piano'), ('violin', 'Violin')], max_length=20)),
            ],
        ),
    ]
